version: '3'

services:
  renovate:
    image: renovate/renovate:34.160.0
    environment:
      - HTTPS_PROXY=nginx:443
      - HTTP_PROXY=nginx:80
      - LOG_LEVEL=debug
      - NO_PROXY=".otp.hu"
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NODE_DEBUG="timer,http node index.js"
      - RENOVATE_CONFIG_FILE=./renovate/renovate-config.js  
    volumes:
     - ./renovate:/mnt/c/Projects/dart-renovate 

  nginx:
    image: nginx
    environment:
     - DEBUG=1
    ports:
     - "80:80"
     - "443:443"