version: '3'

services:
  renovate:
    image: renovate/renovate:latest
    environment:
      - GLOBAL_AGENT.HTTPS_PROXY='https://nginx:443'
      - GLOBAL_AGENT.HTTP_PROXY='http://nginx:80'
      - GLOBAL_AGENT.NO_PROXY='.github.com'
      - LOG_LEVEL=debug
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NODE_DEBUG="timer,http node index.js"
      - RENOVATE_CONFIG_FILE=/mnt/c/Projects/dart-renovate/renovate-config.js  
    volumes:
     - /mnt/c/Projects/dart-renovate:/mnt/c/Projects/dart-renovate 

  nginx:
    image: nginx
    environment:
     - DEBUG=1
    ports:
     - "80:80"
     - "443:443"